[build]
  publish = "."
  command = "echo 'Static frontend deployment - backend runs on Render'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = "*"
